name: angular_analyzer_plugin
version: 0.0.17+6
description: Dart analyzer plugin for Angular 2+
authors:
  - Konstantin Scheglov <scheglov@google.com>
  - Mike Fairhurst <mfairhurst@google.com>
  - Max Kim <maxkim@google.com>
homepage: https://github.com/dart-lang/angular_analyzer_plugin
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  analyzer: '0.34.2'
  plugin: '^0.2.0'
  #  tuple: '^1.0.1' Does not yet support Dart 2
  analyzer_plugin: '0.0.1-alpha.6'
  angular_ast: '^0.5.0'
  meta: ^1.0.2
  yaml: ^2.1.2
  crypto: '>=1.1.1 <3.0.0'
dev_dependencies:
  test_reflective_loader: '^0.1.0'
  test: '^1.2.0'
  mockito: '^3.0.0'
