language: dart
sudo: false
dart:
  - stable
cache:
  directories:
    - $HOME/.pub-cache
before_script:
  - "(cd .. && git clone --depth=10 https://github.com/dart-lang/sdk.git)" 
script: ./tools/travis.sh
env:
  - PACKAGE=analyzer_plugin
  - PACKAGE=server_plugin

