name: angular_analysis_plugin
version: 0.0.8
description: Dart analysis plugin for Angular 2, using new plugin arch
environment:
  sdk: '>=1.24.0-dev.1.0'
dependencies:
  analyzer: '^0.30.0'
  plugin: '^0.2.0'
  html: '^0.12.2'
  tuple: '^1.0.1'
  analyzer_plugin: 0.0.8
  angular_analyzer_plugin: 0.0.8
  angular_analyzer_server_plugin: 0.0.7
dependency_overrides:
  angular_analyzer_plugin:
    path: ../analyzer_plugin
  angular_analyzer_server_plugin:
    path: ../server_plugin
  analyzer:
    path: ../deps/sdk/pkg/analyzer
  analyzer_plugin:
    path: ../deps/sdk/pkg/analyzer_plugin
  front_end:
    path: ../deps/sdk/pkg/front_end
  analysis_server:
    path: ../deps/sdk/pkg/analysis_server
dev_dependencies:
  test_reflective_loader: '^0.1.0'
  typed_mock: '^0.0.4'
  unittest: '^0.11.0'
  test: '^0.12.20'
